-- Gabriel -- The Colony Mind
-- Static database objects. Requires Community Patch 5.x.

INSERT OR REPLACE INTO Colors
(Type, Red, Green, Blue, Alpha) VALUES
('COLOR_GABRIEL_PRIMARY',   0.82, 0.52, 0.12, 1.00),
('COLOR_GABRIEL_SECONDARY', 0.035, 0.045, 0.055, 1.00);

INSERT OR REPLACE INTO PlayerColors
(Type, PrimaryColor, SecondaryColor, TextColor) VALUES
('PLAYERCOLOR_GABRIEL', 'COLOR_GABRIEL_PRIMARY', 'COLOR_GABRIEL_SECONDARY', 'COLOR_PLAYER_WHITE_TEXT');

INSERT OR REPLACE INTO IconTextureAtlases
(Atlas, IconSize, Filename, IconsPerRow, IconsPerColumn) VALUES
('GABRIEL_CIV_ATLAS', 256, 'Gabriel_Civ_256.dds', 1, 1),
('GABRIEL_CIV_ATLAS', 128, 'Gabriel_Civ_128.dds', 1, 1),
('GABRIEL_CIV_ATLAS', 80,  'Gabriel_Civ_80.dds',  1, 1),
('GABRIEL_CIV_ATLAS', 64,  'Gabriel_Civ_64.dds',  1, 1),
('GABRIEL_CIV_ATLAS', 45,  'Gabriel_Civ_45.dds',  1, 1),
('GABRIEL_CIV_ATLAS', 32,  'Gabriel_Civ_32.dds',  1, 1),
('GABRIEL_ALPHA_ATLAS', 128, 'Gabriel_Alpha_128.dds', 1, 1),
('GABRIEL_ALPHA_ATLAS', 64,  'Gabriel_Alpha_64.dds',  1, 1),
('GABRIEL_ALPHA_ATLAS', 48,  'Gabriel_Alpha_48.dds',  1, 1),
('GABRIEL_ALPHA_ATLAS', 32,  'Gabriel_Alpha_32.dds',  1, 1),
('GABRIEL_ALPHA_ATLAS', 24,  'Gabriel_Alpha_24.dds',  1, 1),
('GABRIEL_ALPHA_ATLAS', 16,  'Gabriel_Alpha_16.dds',  1, 1),
('GABRIEL_LEADER_ATLAS', 256, 'Gabriel_Leader_256.dds', 1, 1),
('GABRIEL_LEADER_ATLAS', 128, 'Gabriel_Leader_128.dds', 1, 1),
('GABRIEL_LEADER_ATLAS', 64,  'Gabriel_Leader_64.dds',  1, 1),
('GABRIEL_OBJECT_ATLAS', 256, 'Gabriel_Objects_256.dds', 4, 1),
('GABRIEL_OBJECT_ATLAS', 128, 'Gabriel_Objects_128.dds', 4, 1),
('GABRIEL_OBJECT_ATLAS', 80,  'Gabriel_Objects_80.dds',  4, 1),
('GABRIEL_OBJECT_ATLAS', 64,  'Gabriel_Objects_64.dds',  4, 1),
('GABRIEL_OBJECT_ATLAS', 45,  'Gabriel_Objects_45.dds',  4, 1),
('GABRIEL_OBJECT_ATLAS', 32,  'Gabriel_Objects_32.dds',  4, 1);

INSERT INTO Traits
(Type, Description, ShortDescription) VALUES
('TRAIT_GABRIEL_COLONY_NETWORK', 'TXT_KEY_TRAIT_GABRIEL_COLONY_NETWORK', 'TXT_KEY_TRAIT_GABRIEL_COLONY_NETWORK_SHORT');

INSERT INTO Leaders
(Type, Description, Civilopedia, CivilopediaTag, ArtDefineTag,
 VictoryCompetitiveness, WonderCompetitiveness, MinorCivCompetitiveness,
 Boldness, DiploBalance, WarmongerHate, WorkAgainstWillingness,
 WorkWithWillingness, DenounceWillingness, DoFWillingness, Loyalty,
 Neediness, Forgiveness, Chattiness, Meanness, PortraitIndex, IconAtlas)
SELECT
 'LEADER_GABRIEL_COLONY_MIND', 'TXT_KEY_LEADER_GABRIEL',
 'TXT_KEY_LEADER_GABRIEL_PEDIA', 'TXT_KEY_CIVILOPEDIA_LEADERS_GABRIEL',
 'Gabriel_LeaderScene.xml',
 8, 4, 8, 3, 8, 9, 6, 9, 6, 8, 9, 4, 5, 4, 3,
 0, 'GABRIEL_LEADER_ATLAS'
FROM Leaders WHERE Type = 'LEADER_WASHINGTON';

INSERT INTO Leader_Traits VALUES
('LEADER_GABRIEL_COLONY_MIND', 'TRAIT_GABRIEL_COLONY_NETWORK');

INSERT INTO Leader_MajorCivApproachBiases
SELECT 'LEADER_GABRIEL_COLONY_MIND', MajorCivApproachType, Bias
FROM Leader_MajorCivApproachBiases WHERE LeaderType = 'LEADER_HIAWATHA';
UPDATE Leader_MajorCivApproachBiases SET Bias = 2
WHERE LeaderType = 'LEADER_GABRIEL_COLONY_MIND' AND MajorCivApproachType = 'MAJOR_CIV_APPROACH_WAR';
UPDATE Leader_MajorCivApproachBiases SET Bias = 8
WHERE LeaderType = 'LEADER_GABRIEL_COLONY_MIND' AND MajorCivApproachType IN ('MAJOR_CIV_APPROACH_FRIENDLY', 'MAJOR_CIV_APPROACH_AFRAID');

INSERT INTO Leader_MinorCivApproachBiases
SELECT 'LEADER_GABRIEL_COLONY_MIND', MinorCivApproachType, Bias
FROM Leader_MinorCivApproachBiases WHERE LeaderType = 'LEADER_HIAWATHA';

INSERT INTO Leader_Flavors
SELECT 'LEADER_GABRIEL_COLONY_MIND', FlavorType, Flavor
FROM Leader_Flavors WHERE LeaderType = 'LEADER_HIAWATHA';
UPDATE Leader_Flavors SET Flavor = 10 WHERE LeaderType = 'LEADER_GABRIEL_COLONY_MIND' AND FlavorType IN ('FLAVOR_SCIENCE', 'FLAVOR_DEFENSE');
UPDATE Leader_Flavors SET Flavor = 9  WHERE LeaderType = 'LEADER_GABRIEL_COLONY_MIND' AND FlavorType IN ('FLAVOR_RECON', 'FLAVOR_TILE_IMPROVEMENT');
UPDATE Leader_Flavors SET Flavor = 8  WHERE LeaderType = 'LEADER_GABRIEL_COLONY_MIND' AND FlavorType IN ('FLAVOR_RANGED', 'FLAVOR_CITY_DEFENSE', 'FLAVOR_DIPLOMACY');
UPDATE Leader_Flavors SET Flavor = 3  WHERE LeaderType = 'LEADER_GABRIEL_COLONY_MIND' AND FlavorType IN ('FLAVOR_OFFENSE', 'FLAVOR_EXPANSION');

INSERT INTO Civilizations
(Type, Description, Civilopedia, CivilopediaTag, Strategy, Playable, AIPlayable,
 ShortDescription, Adjective, DefaultPlayerColor, ArtDefineTag, ArtStyleType,
 ArtStyleSuffix, ArtStylePrefix, PortraitIndex, IconAtlas, AlphaIconAtlas,
 MapImage, DawnOfManQuote, DawnOfManImage, DawnOfManAudio, SoundtrackTag)
SELECT
 'CIVILIZATION_GABRIEL_COLONY', 'TXT_KEY_CIV_GABRIEL_DESC',
 'TXT_KEY_CIV_GABRIEL_PEDIA', 'TXT_KEY_CIV5_GABRIEL',
 'TXT_KEY_CIV_GABRIEL_STRATEGY', 1, 1,
 'TXT_KEY_CIV_GABRIEL_SHORT_DESC', 'TXT_KEY_CIV_GABRIEL_ADJECTIVE',
 'PLAYERCOLOR_GABRIEL', ArtDefineTag, ArtStyleType, ArtStyleSuffix, ArtStylePrefix,
 0, 'GABRIEL_CIV_ATLAS', 'GABRIEL_ALPHA_ATLAS', 'Gabriel_Map.dds',
 'TXT_KEY_CIV5_DOM_GABRIEL_TEXT', 'Gabriel_Map.dds', '', SoundtrackTag
FROM Civilizations WHERE Type = 'CIVILIZATION_AMERICA';

INSERT INTO Civilization_Leaders VALUES
('CIVILIZATION_GABRIEL_COLONY', 'LEADER_GABRIEL_COLONY_MIND');
INSERT INTO Civilization_FreeBuildingClasses VALUES
('CIVILIZATION_GABRIEL_COLONY', 'BUILDINGCLASS_PALACE');
INSERT INTO Civilization_FreeTechs VALUES
('CIVILIZATION_GABRIEL_COLONY', 'TECH_AGRICULTURE');
-- Mirror the standard CP starting package. The selected era supplies the
-- ordinary escort separately; adding another unit here creates an extra start.
INSERT INTO Civilization_FreeUnits (CivilizationType, UnitClassType, UnitAIType, Count)
SELECT 'CIVILIZATION_GABRIEL_COLONY', UnitClassType, UnitAIType, Count
FROM Civilization_FreeUnits
WHERE CivilizationType = 'CIVILIZATION_AMERICA';
INSERT INTO Civilization_Start_Along_Ocean VALUES
('CIVILIZATION_GABRIEL_COLONY', 0);

INSERT INTO Civilization_CityNames VALUES
('CIVILIZATION_GABRIEL_COLONY', 'TXT_KEY_CITY_GABRIEL_PRIME_CHAMBER'),
('CIVILIZATION_GABRIEL_COLONY', 'TXT_KEY_CITY_GABRIEL_FORMICARIUM'),
('CIVILIZATION_GABRIEL_COLONY', 'TXT_KEY_CITY_GABRIEL_AMBER_VAULT'),
('CIVILIZATION_GABRIEL_COLONY', 'TXT_KEY_CITY_GABRIEL_SIX_PATHS'),
('CIVILIZATION_GABRIEL_COLONY', 'TXT_KEY_CITY_GABRIEL_QUIET_REACH'),
('CIVILIZATION_GABRIEL_COLONY', 'TXT_KEY_CITY_GABRIEL_DEEP_NURSERY'),
('CIVILIZATION_GABRIEL_COLONY', 'TXT_KEY_CITY_GABRIEL_WATCHER_HILL'),
('CIVILIZATION_GABRIEL_COLONY', 'TXT_KEY_CITY_GABRIEL_LONG_TRAIL'),
('CIVILIZATION_GABRIEL_COLONY', 'TXT_KEY_CITY_GABRIEL_PATIENT_GATE'),
('CIVILIZATION_GABRIEL_COLONY', 'TXT_KEY_CITY_GABRIEL_SHARED_PURPOSE'),
('CIVILIZATION_GABRIEL_COLONY', 'TXT_KEY_CITY_GABRIEL_ROOT_COUNCIL'),
('CIVILIZATION_GABRIEL_COLONY', 'TXT_KEY_CITY_GABRIEL_LANTERN_NEST');

INSERT INTO Civilization_SpyNames VALUES
('CIVILIZATION_GABRIEL_COLONY', 'TXT_KEY_SPY_GABRIEL_SCOUT_ONE'),
('CIVILIZATION_GABRIEL_COLONY', 'TXT_KEY_SPY_GABRIEL_SCOUT_TWO'),
('CIVILIZATION_GABRIEL_COLONY', 'TXT_KEY_SPY_GABRIEL_SCOUT_THREE'),
('CIVILIZATION_GABRIEL_COLONY', 'TXT_KEY_SPY_GABRIEL_SCOUT_FOUR');

-- Colony Node: Lua places it, while CP natively supplies its yields and vision.
CREATE TEMP TABLE Gabriel_NodeCopy AS
SELECT * FROM Improvements WHERE Type = 'IMPROVEMENT_TRADING_POST';
UPDATE Gabriel_NodeCopy SET
 ID = NULL,
 Type = 'IMPROVEMENT_GABRIEL_COLONY_NODE',
 Description = 'TXT_KEY_IMPROVEMENT_GABRIEL_COLONY_NODE',
 Civilopedia = 'TXT_KEY_IMPROVEMENT_GABRIEL_COLONY_NODE_PEDIA',
 Help = 'TXT_KEY_IMPROVEMENT_GABRIEL_COLONY_NODE_HELP',
 SpecificCivRequired = 1,
 CivilizationType = 'CIVILIZATION_GABRIEL_COLONY',
 -- Reuse the stock Fort landmark so a placed Node is unmistakable on-map.
 -- This is visual only; DefenseModifier remains zero below.
 ArtDefineTag = 'ART_DEF_IMPROVEMENT_FORT',
 OutsideBorders = 1,
 IgnoreOwnership = 0,
 CreatedByGreatPerson = 0,
 DestroyedWhenPillaged = 0,
 Permanent = 0,
 NoTwoAdjacent = 0,
 DefenseModifier = 0,
 PillageGold = 0,
 GoldMaintenance = 0,
 GrantsVisionXTiles = 1,
 PortraitIndex = 2,
 IconAtlas = 'GABRIEL_OBJECT_ATLAS';
INSERT INTO Improvements SELECT * FROM Gabriel_NodeCopy;
DROP TABLE Gabriel_NodeCopy;

INSERT INTO Improvement_Yields VALUES
('IMPROVEMENT_GABRIEL_COLONY_NODE', 'YIELD_SCIENCE', 1),
('IMPROVEMENT_GABRIEL_COLONY_NODE', 'YIELD_PRODUCTION', 1);

-- Swarm Host dynamically inherits the active CP Composite Bowman row.
CREATE TEMP TABLE Gabriel_SwarmHostCopy AS
SELECT * FROM Units WHERE Type = 'UNIT_COMPOSITE_BOWMAN';
UPDATE Gabriel_SwarmHostCopy SET
 ID = NULL,
 Type = 'UNIT_GABRIEL_SWARM_HOST',
 Description = 'TXT_KEY_UNIT_GABRIEL_SWARM_HOST',
 Civilopedia = 'TXT_KEY_UNIT_GABRIEL_SWARM_HOST_PEDIA',
 Strategy = 'TXT_KEY_UNIT_GABRIEL_SWARM_HOST_STRATEGY',
 Help = 'TXT_KEY_UNIT_GABRIEL_SWARM_HOST_HELP',
 RangedCombat = MAX(1, RangedCombat - 1),
 PortraitIndex = 0,
 IconAtlas = 'GABRIEL_OBJECT_ATLAS';
INSERT INTO Units SELECT * FROM Gabriel_SwarmHostCopy;
DROP TABLE Gabriel_SwarmHostCopy;

INSERT INTO Unit_AITypes SELECT 'UNIT_GABRIEL_SWARM_HOST', UnitAIType FROM Unit_AITypes WHERE UnitType = 'UNIT_COMPOSITE_BOWMAN';
INSERT INTO Unit_ClassUpgrades SELECT 'UNIT_GABRIEL_SWARM_HOST', UnitClassType FROM Unit_ClassUpgrades WHERE UnitType = 'UNIT_COMPOSITE_BOWMAN';
INSERT INTO Unit_Flavors SELECT 'UNIT_GABRIEL_SWARM_HOST', FlavorType, Flavor FROM Unit_Flavors WHERE UnitType = 'UNIT_COMPOSITE_BOWMAN';
INSERT INTO Unit_FreePromotions SELECT 'UNIT_GABRIEL_SWARM_HOST', PromotionType FROM Unit_FreePromotions WHERE UnitType = 'UNIT_COMPOSITE_BOWMAN';
INSERT INTO Civilization_UnitClassOverrides VALUES
('CIVILIZATION_GABRIEL_COLONY', 'UNITCLASS_COMPOSITE_BOWMAN', 'UNIT_GABRIEL_SWARM_HOST');

-- Colony Nexus dynamically inherits the active CP University row and all
-- University relationship rows that carry its ordinary gameplay effects.
CREATE TEMP TABLE Gabriel_NexusCopy AS
SELECT * FROM Buildings WHERE Type = 'BUILDING_UNIVERSITY';
UPDATE Gabriel_NexusCopy SET
 ID = NULL,
 Type = 'BUILDING_GABRIEL_COLONY_NEXUS',
 Description = 'TXT_KEY_BUILDING_GABRIEL_COLONY_NEXUS',
 Civilopedia = 'TXT_KEY_BUILDING_GABRIEL_COLONY_NEXUS_PEDIA',
 Strategy = 'TXT_KEY_BUILDING_GABRIEL_COLONY_NEXUS_STRATEGY',
 Help = 'TXT_KEY_BUILDING_GABRIEL_COLONY_NEXUS_HELP',
 GreatPeopleRateChange = GreatPeopleRateChange + 1,
 PortraitIndex = 1,
 IconAtlas = 'GABRIEL_OBJECT_ATLAS';
INSERT INTO Buildings SELECT * FROM Gabriel_NexusCopy;
DROP TABLE Gabriel_NexusCopy;

INSERT INTO Building_ClassesNeededInCity SELECT 'BUILDING_GABRIEL_COLONY_NEXUS', BuildingClassType FROM Building_ClassesNeededInCity WHERE BuildingType = 'BUILDING_UNIVERSITY';
INSERT INTO Building_Flavors SELECT 'BUILDING_GABRIEL_COLONY_NEXUS', FlavorType, Flavor FROM Building_Flavors WHERE BuildingType = 'BUILDING_UNIVERSITY';
INSERT INTO Building_YieldChanges SELECT 'BUILDING_GABRIEL_COLONY_NEXUS', YieldType, Yield FROM Building_YieldChanges WHERE BuildingType = 'BUILDING_UNIVERSITY';
INSERT INTO Building_YieldModifiers SELECT 'BUILDING_GABRIEL_COLONY_NEXUS', YieldType, Yield FROM Building_YieldModifiers WHERE BuildingType = 'BUILDING_UNIVERSITY';
INSERT INTO Building_FeatureYieldChanges SELECT 'BUILDING_GABRIEL_COLONY_NEXUS', FeatureType, YieldType, Yield FROM Building_FeatureYieldChanges WHERE BuildingType = 'BUILDING_UNIVERSITY';
INSERT INTO Building_TerrainYieldChanges SELECT 'BUILDING_GABRIEL_COLONY_NEXUS', TerrainType, YieldType, Yield FROM Building_TerrainYieldChanges WHERE BuildingType = 'BUILDING_UNIVERSITY';
INSERT INTO Building_ResourceYieldChanges SELECT 'BUILDING_GABRIEL_COLONY_NEXUS', ResourceType, YieldType, Yield FROM Building_ResourceYieldChanges WHERE BuildingType = 'BUILDING_UNIVERSITY';
INSERT INTO Building_SpecialistYieldChanges SELECT 'BUILDING_GABRIEL_COLONY_NEXUS', SpecialistType, YieldType, Yield FROM Building_SpecialistYieldChanges WHERE BuildingType = 'BUILDING_UNIVERSITY';
INSERT INTO Building_TechEnhancedYieldChanges (BuildingType, YieldType, Yield, TechType)
SELECT 'BUILDING_GABRIEL_COLONY_NEXUS', YieldType, Yield, TechType
FROM Building_TechEnhancedYieldChanges WHERE BuildingType = 'BUILDING_UNIVERSITY';
INSERT INTO Civilization_BuildingClassOverrides VALUES
('CIVILIZATION_GABRIEL_COLONY', 'BUILDINGCLASS_UNIVERSITY', 'BUILDING_GABRIEL_COLONY_NEXUS');

-- Dynamic promotions. AttackMod is an offensive-only strength modifier, which
-- is CP's stable equivalent of approximately +5% outgoing damage.
INSERT INTO UnitPromotions
(Type, Description, Help, CannotBeChosen, LostWithUpgrade, CombatPercent, AttackMod,
 FriendlyHealChange, NeutralHealChange, EnemyHealChange, PortraitIndex, IconAtlas, PediaType, PediaEntry) VALUES
('PROMOTION_GABRIEL_COLONY_NETWORK', 'TXT_KEY_PROMOTION_GABRIEL_COLONY_NETWORK', 'TXT_KEY_PROMOTION_GABRIEL_COLONY_NETWORK_HELP', 1, 0, 3, 5, 3, 3, 3, 3, 'GABRIEL_OBJECT_ATLAS', 'PEDIA_ATTRIBUTES', 'TXT_KEY_PROMOTION_GABRIEL_COLONY_NETWORK'),
('PROMOTION_GABRIEL_SWARM_REINFORCEMENT', 'TXT_KEY_PROMOTION_GABRIEL_SWARM_REINFORCEMENT', 'TXT_KEY_PROMOTION_GABRIEL_SWARM_REINFORCEMENT_HELP', 1, 0, 8, 0, 0, 0, 0, 3, 'GABRIEL_OBJECT_ATLAS', 'PEDIA_ATTRIBUTES', 'TXT_KEY_PROMOTION_GABRIEL_SWARM_REINFORCEMENT'),
('PROMOTION_GABRIEL_INFESTATION_SOURCE', 'TXT_KEY_PROMOTION_GABRIEL_INFESTATION_SOURCE', 'TXT_KEY_PROMOTION_GABRIEL_INFESTATION_SOURCE_HELP', 1, 0, 0, 0, 0, 0, 0, 3, 'GABRIEL_OBJECT_ATLAS', 'PEDIA_ATTRIBUTES', 'TXT_KEY_PROMOTION_GABRIEL_INFESTATION_SOURCE'),
('PROMOTION_GABRIEL_INFESTATION_1', 'TXT_KEY_PROMOTION_GABRIEL_INFESTATION_1', 'TXT_KEY_PROMOTION_GABRIEL_INFESTATION_1_HELP', 1, 0, -5, 0, 0, 0, 0, 3, 'GABRIEL_OBJECT_ATLAS', 'PEDIA_ATTRIBUTES', 'TXT_KEY_PROMOTION_GABRIEL_INFESTATION_1'),
('PROMOTION_GABRIEL_INFESTATION_2', 'TXT_KEY_PROMOTION_GABRIEL_INFESTATION_2', 'TXT_KEY_PROMOTION_GABRIEL_INFESTATION_2_HELP', 1, 0, -10, 0, 0, 0, 0, 3, 'GABRIEL_OBJECT_ATLAS', 'PEDIA_ATTRIBUTES', 'TXT_KEY_PROMOTION_GABRIEL_INFESTATION_2'),
('PROMOTION_GABRIEL_INFESTATION_3', 'TXT_KEY_PROMOTION_GABRIEL_INFESTATION_3', 'TXT_KEY_PROMOTION_GABRIEL_INFESTATION_3_HELP', 1, 0, -15, 0, 0, 0, 0, 3, 'GABRIEL_OBJECT_ATLAS', 'PEDIA_ATTRIBUTES', 'TXT_KEY_PROMOTION_GABRIEL_INFESTATION_3');

INSERT INTO UnitPromotions
(Type, Description, Help, CannotBeChosen, LostWithUpgrade, SeeInvisible, PortraitIndex, IconAtlas, PediaType, PediaEntry) VALUES
('PROMOTION_GABRIEL_NEXUS_DETECTION', 'TXT_KEY_PROMOTION_GABRIEL_NEXUS_DETECTION', 'TXT_KEY_PROMOTION_GABRIEL_NEXUS_DETECTION_HELP', 1, 0, 'INVISIBLE_SUBMARINE', 3, 'GABRIEL_OBJECT_ATLAS', 'PEDIA_ATTRIBUTES', 'TXT_KEY_PROMOTION_GABRIEL_NEXUS_DETECTION');

INSERT INTO Unit_FreePromotions VALUES
('UNIT_GABRIEL_SWARM_HOST', 'PROMOTION_GABRIEL_INFESTATION_SOURCE');

-- Six geometry-capped city network tiers and six Nexus flat-science tiers.
INSERT INTO BuildingClasses
(Type, DefaultBuilding, Description, MaxGlobalInstances, MaxTeamInstances, MaxPlayerInstances) VALUES
('BUILDINGCLASS_GABRIEL_NETWORK_1', 'BUILDING_GABRIEL_NETWORK_1', 'TXT_KEY_BUILDING_GABRIEL_NETWORK_DUMMY', -1, -1, -1),
('BUILDINGCLASS_GABRIEL_NETWORK_2', 'BUILDING_GABRIEL_NETWORK_2', 'TXT_KEY_BUILDING_GABRIEL_NETWORK_DUMMY', -1, -1, -1),
('BUILDINGCLASS_GABRIEL_NETWORK_3', 'BUILDING_GABRIEL_NETWORK_3', 'TXT_KEY_BUILDING_GABRIEL_NETWORK_DUMMY', -1, -1, -1),
('BUILDINGCLASS_GABRIEL_NETWORK_4', 'BUILDING_GABRIEL_NETWORK_4', 'TXT_KEY_BUILDING_GABRIEL_NETWORK_DUMMY', -1, -1, -1),
('BUILDINGCLASS_GABRIEL_NETWORK_5', 'BUILDING_GABRIEL_NETWORK_5', 'TXT_KEY_BUILDING_GABRIEL_NETWORK_DUMMY', -1, -1, -1),
('BUILDINGCLASS_GABRIEL_NETWORK_6', 'BUILDING_GABRIEL_NETWORK_6', 'TXT_KEY_BUILDING_GABRIEL_NETWORK_DUMMY', -1, -1, -1),
('BUILDINGCLASS_GABRIEL_NEXUS_SCIENCE_1', 'BUILDING_GABRIEL_NEXUS_SCIENCE_1', 'TXT_KEY_BUILDING_GABRIEL_NETWORK_DUMMY', -1, -1, -1),
('BUILDINGCLASS_GABRIEL_NEXUS_SCIENCE_2', 'BUILDING_GABRIEL_NEXUS_SCIENCE_2', 'TXT_KEY_BUILDING_GABRIEL_NETWORK_DUMMY', -1, -1, -1),
('BUILDINGCLASS_GABRIEL_NEXUS_SCIENCE_3', 'BUILDING_GABRIEL_NEXUS_SCIENCE_3', 'TXT_KEY_BUILDING_GABRIEL_NETWORK_DUMMY', -1, -1, -1),
('BUILDINGCLASS_GABRIEL_NEXUS_SCIENCE_4', 'BUILDING_GABRIEL_NEXUS_SCIENCE_4', 'TXT_KEY_BUILDING_GABRIEL_NETWORK_DUMMY', -1, -1, -1),
('BUILDINGCLASS_GABRIEL_NEXUS_SCIENCE_5', 'BUILDING_GABRIEL_NEXUS_SCIENCE_5', 'TXT_KEY_BUILDING_GABRIEL_NETWORK_DUMMY', -1, -1, -1),
('BUILDINGCLASS_GABRIEL_NEXUS_SCIENCE_6', 'BUILDING_GABRIEL_NEXUS_SCIENCE_6', 'TXT_KEY_BUILDING_GABRIEL_NETWORK_DUMMY', -1, -1, -1);

INSERT INTO Buildings
(Type, BuildingClass, Description, Cost, FaithCost, GoldMaintenance, PrereqTech,
 NeverCapture, NukeImmune, ConquestProb, GreatWorkCount, IsDummy,
 BuildingDefenseModifier, PortraitIndex, IconAtlas) VALUES
('BUILDING_GABRIEL_NETWORK_1', 'BUILDINGCLASS_GABRIEL_NETWORK_1', 'TXT_KEY_BUILDING_GABRIEL_NETWORK_DUMMY', -1, -1, 0, NULL, 1, 1, 0, -1, 1, 1, 0, 'GABRIEL_OBJECT_ATLAS'),
('BUILDING_GABRIEL_NETWORK_2', 'BUILDINGCLASS_GABRIEL_NETWORK_2', 'TXT_KEY_BUILDING_GABRIEL_NETWORK_DUMMY', -1, -1, 0, NULL, 1, 1, 0, -1, 1, 2, 0, 'GABRIEL_OBJECT_ATLAS'),
('BUILDING_GABRIEL_NETWORK_3', 'BUILDINGCLASS_GABRIEL_NETWORK_3', 'TXT_KEY_BUILDING_GABRIEL_NETWORK_DUMMY', -1, -1, 0, NULL, 1, 1, 0, -1, 1, 3, 0, 'GABRIEL_OBJECT_ATLAS'),
('BUILDING_GABRIEL_NETWORK_4', 'BUILDINGCLASS_GABRIEL_NETWORK_4', 'TXT_KEY_BUILDING_GABRIEL_NETWORK_DUMMY', -1, -1, 0, NULL, 1, 1, 0, -1, 1, 4, 0, 'GABRIEL_OBJECT_ATLAS'),
('BUILDING_GABRIEL_NETWORK_5', 'BUILDINGCLASS_GABRIEL_NETWORK_5', 'TXT_KEY_BUILDING_GABRIEL_NETWORK_DUMMY', -1, -1, 0, NULL, 1, 1, 0, -1, 1, 5, 0, 'GABRIEL_OBJECT_ATLAS'),
('BUILDING_GABRIEL_NETWORK_6', 'BUILDINGCLASS_GABRIEL_NETWORK_6', 'TXT_KEY_BUILDING_GABRIEL_NETWORK_DUMMY', -1, -1, 0, NULL, 1, 1, 0, -1, 1, 6, 0, 'GABRIEL_OBJECT_ATLAS'),
('BUILDING_GABRIEL_NEXUS_SCIENCE_1', 'BUILDINGCLASS_GABRIEL_NEXUS_SCIENCE_1', 'TXT_KEY_BUILDING_GABRIEL_NETWORK_DUMMY', -1, -1, 0, NULL, 1, 1, 0, -1, 1, 0, 0, 'GABRIEL_OBJECT_ATLAS'),
('BUILDING_GABRIEL_NEXUS_SCIENCE_2', 'BUILDINGCLASS_GABRIEL_NEXUS_SCIENCE_2', 'TXT_KEY_BUILDING_GABRIEL_NETWORK_DUMMY', -1, -1, 0, NULL, 1, 1, 0, -1, 1, 0, 0, 'GABRIEL_OBJECT_ATLAS'),
('BUILDING_GABRIEL_NEXUS_SCIENCE_3', 'BUILDINGCLASS_GABRIEL_NEXUS_SCIENCE_3', 'TXT_KEY_BUILDING_GABRIEL_NETWORK_DUMMY', -1, -1, 0, NULL, 1, 1, 0, -1, 1, 0, 0, 'GABRIEL_OBJECT_ATLAS'),
('BUILDING_GABRIEL_NEXUS_SCIENCE_4', 'BUILDINGCLASS_GABRIEL_NEXUS_SCIENCE_4', 'TXT_KEY_BUILDING_GABRIEL_NETWORK_DUMMY', -1, -1, 0, NULL, 1, 1, 0, -1, 1, 0, 0, 'GABRIEL_OBJECT_ATLAS'),
('BUILDING_GABRIEL_NEXUS_SCIENCE_5', 'BUILDINGCLASS_GABRIEL_NEXUS_SCIENCE_5', 'TXT_KEY_BUILDING_GABRIEL_NETWORK_DUMMY', -1, -1, 0, NULL, 1, 1, 0, -1, 1, 0, 0, 'GABRIEL_OBJECT_ATLAS'),
('BUILDING_GABRIEL_NEXUS_SCIENCE_6', 'BUILDINGCLASS_GABRIEL_NEXUS_SCIENCE_6', 'TXT_KEY_BUILDING_GABRIEL_NETWORK_DUMMY', -1, -1, 0, NULL, 1, 1, 0, -1, 1, 0, 0, 'GABRIEL_OBJECT_ATLAS');

INSERT INTO Building_YieldModifiers VALUES
('BUILDING_GABRIEL_NETWORK_1', 'YIELD_SCIENCE', 1),
('BUILDING_GABRIEL_NETWORK_2', 'YIELD_SCIENCE', 2),
('BUILDING_GABRIEL_NETWORK_3', 'YIELD_SCIENCE', 3),
('BUILDING_GABRIEL_NETWORK_4', 'YIELD_SCIENCE', 4),
('BUILDING_GABRIEL_NETWORK_5', 'YIELD_SCIENCE', 5),
('BUILDING_GABRIEL_NETWORK_6', 'YIELD_SCIENCE', 6);

INSERT INTO Building_YieldChanges VALUES
('BUILDING_GABRIEL_NEXUS_SCIENCE_1', 'YIELD_SCIENCE', 1),
('BUILDING_GABRIEL_NEXUS_SCIENCE_2', 'YIELD_SCIENCE', 2),
('BUILDING_GABRIEL_NEXUS_SCIENCE_3', 'YIELD_SCIENCE', 3),
('BUILDING_GABRIEL_NEXUS_SCIENCE_4', 'YIELD_SCIENCE', 4),
('BUILDING_GABRIEL_NEXUS_SCIENCE_5', 'YIELD_SCIENCE', 5),
('BUILDING_GABRIEL_NEXUS_SCIENCE_6', 'YIELD_SCIENCE', 6);

-- Diplomacy responses use Gabriel-specific localization and never Washington's.
INSERT INTO Diplomacy_Responses (LeaderType, ResponseType, Response, Bias) VALUES
('LEADER_GABRIEL_COLONY_MIND', 'RESPONSE_FIRST_GREETING', 'TXT_KEY_LEADER_GABRIEL_FIRSTGREETING%', 500),
('LEADER_GABRIEL_COLONY_MIND', 'RESPONSE_GREETING_POLITE_HELLO', 'TXT_KEY_LEADER_GABRIEL_GREETING_FRIENDLY%', 500),
('LEADER_GABRIEL_COLONY_MIND', 'RESPONSE_GREETING_NEUTRAL_HELLO', 'TXT_KEY_LEADER_GABRIEL_GREETING_NEUTRAL%', 500),
('LEADER_GABRIEL_COLONY_MIND', 'RESPONSE_GREETING_HOSTILE_HELLO', 'TXT_KEY_LEADER_GABRIEL_GREETING_HOSTILE%', 500),
('LEADER_GABRIEL_COLONY_MIND', 'RESPONSE_DOW_GENERIC', 'TXT_KEY_LEADER_GABRIEL_DECLAREWAR%', 500),
('LEADER_GABRIEL_COLONY_MIND', 'RESPONSE_ATTACKED_HOSTILE', 'TXT_KEY_LEADER_GABRIEL_ATTACKED%', 500),
('LEADER_GABRIEL_COLONY_MIND', 'RESPONSE_PEACE_MADE_BY_HUMAN_GRACIOUS', 'TXT_KEY_LEADER_GABRIEL_LOSEWAR%', 500),
('LEADER_GABRIEL_COLONY_MIND', 'RESPONSE_WINNER_PEACE_OFFER', 'TXT_KEY_LEADER_GABRIEL_WINWAR%', 500),
('LEADER_GABRIEL_COLONY_MIND', 'RESPONSE_DEFEATED', 'TXT_KEY_LEADER_GABRIEL_DEFEATED%', 500);
