INSERT OR REPLACE INTO Language_en_US (Tag, Text) VALUES
('TXT_KEY_CIV_GABRIEL_DESC', 'The Colony'),
('TXT_KEY_CIV_GABRIEL_SHORT_DESC', 'The Colony'),
('TXT_KEY_CIV_GABRIEL_ADJECTIVE', 'Colony'),
('TXT_KEY_LEADER_GABRIEL', 'Gabriel'),
('TXT_KEY_TRAIT_GABRIEL_COLONY_NETWORK', 'Cities prepare Colony Nodes every 30 turns (Standard). Nodes provide Science, Production and vision, strengthen nearby troops, and boost adjacent cities. See Civilopedia for full bonuses.'),
('TXT_KEY_TRAIT_GABRIEL_COLONY_NETWORK_SHORT', 'Colony Network'),
('TXT_KEY_TRAIT_GABRIEL_COLONY_NETWORK_HELP', 'Every city generates a Colony Node every 30 turns on Standard speed. Colony Nodes provide +1 [ICON_RESEARCH] Science, +1 [ICON_PRODUCTION] Production, and vision of adjacent tiles. Military units within their influence gain +3% Combat Strength, +5% attacking strength, and +3 healing. Each active Node adjacent to a city provides +1% [ICON_RESEARCH] Science and +1% City Defensive Strength.'),

('TXT_KEY_CIV_GABRIEL_PEDIA', 'The Colony is a distributed civilization organized around observation, preparation, and shared purpose. Gabriel does not command it as a monarch commands subjects. He listens to thousands of small signals, arranges the conditions in which each part can act, and lets order grow from connection. Its roads resemble trails, its universities are living information nexuses, and its border works descend into chambered formicaria beneath the soil.[NEWLINE][NEWLINE]No individual Node is overwhelming. Together they form a territorial intelligence: scouts can see farther, defenders recover faster, and cities turn patient preparation into knowledge and resilience. The Colony avoids unnecessary risk, preferring to understand an enemy, weaken it, and counterattack from ground prepared long before war began.'),
('TXT_KEY_CIV_GABRIEL_STRATEGY', 'Prepare, connect, observe, weaken, and counterattack. Establish Colony Nodes beside important cities and along likely invasion routes. Their modest yields mature into percentage Science and city defense, while Colony Nexuses add flat Science. Fight inside overlapping territorial coverage, but remember that the military bonus never stacks. Swarm Hosts wear down dangerous units with Infestation before the rest of the army commits. Pillaged Nodes shut down every network effect, so protect workers and repair critical links quickly. Science is the strongest victory route; Diplomacy is also strong, while Domination works best as a counteroffensive.'),
('TXT_KEY_CIV5_DOM_GABRIEL_TEXT', 'Gabriel, the Colony Mind: yours is not a realm of isolated cities, but a patient living network. Let every trail carry knowledge, every chamber preserve strength, and every watcher prepare the ground before danger arrives. Others will gamble armies against uncertainty. You will have already measured the field. Connect the Colony, observe without rest, and ensure that many minds act with one purpose.'),

('TXT_KEY_LEADER_GABRIEL_PEDIA', 'Gabriel is the Colony''s interpreter, naturalist, and strategist. He studies myrmecology not as a metaphor for obedience but as proof that resilient order can emerge from innumerable informed decisions. Quiet and analytical, he prefers durable friendships, distrusts reckless conquerors, and rarely threatens an opponent without first preparing the terrain on which the threat would be carried out.[NEWLINE][NEWLINE]Gabriel''s authority is practical rather than ceremonial. He maps resources and risk, places information where it will be needed, and allows local initiative within a shared purpose. To him, victory is not a heroic gamble. It is the result that remains after uncertainty has been removed.'),
('TXT_KEY_CIVILOPEDIA_LEADERS_GABRIEL_NAME', 'Gabriel'),
('TXT_KEY_CIVILOPEDIA_LEADERS_GABRIEL_SUBTITLE', 'The Colony Mind'),
('TXT_KEY_CIVILOPEDIA_LEADERS_GABRIEL_LIVED', 'The Age of Convergence'),
('TXT_KEY_CIVILOPEDIA_LEADERS_GABRIEL_TITLES_1', 'Interpreter of the Colony'),
('TXT_KEY_CIVILOPEDIA_LEADERS_GABRIEL_TITLES_2', 'Keeper of the Long Trail'),
('TXT_KEY_CIVILOPEDIA_LEADERS_GABRIEL_HEADING_1', 'The Colony Mind'),
('TXT_KEY_CIVILOPEDIA_LEADERS_GABRIEL_TEXT_1', 'Gabriel is the Colony''s interpreter, naturalist, and strategist. He studies myrmecology not as a metaphor for obedience, but as proof that resilient order can emerge from innumerable informed decisions. Quiet and analytical, he prefers durable friendships and distrusts reckless conquerors.'),
('TXT_KEY_CIVILOPEDIA_LEADERS_GABRIEL_HEADING_2', 'Authority Through Preparation'),
('TXT_KEY_CIVILOPEDIA_LEADERS_GABRIEL_TEXT_2', 'Gabriel''s authority is practical rather than ceremonial. He maps resources and risk, places information where it will be needed, and allows local initiative within a shared purpose. He rarely threatens an opponent without first preparing the terrain on which that threat would be carried out.'),
('TXT_KEY_CIVILOPEDIA_LEADERS_GABRIEL_HEADING_3', 'Many Minds, One Purpose'),
('TXT_KEY_CIVILOPEDIA_LEADERS_GABRIEL_TEXT_3', 'To Gabriel, victory is not a heroic gamble. It is the result that remains after uncertainty has been removed. Every Colony Node is therefore both infrastructure and argument: knowledge shared early becomes strength available exactly when required.'),
('TXT_KEY_CIVILOPEDIA_LEADERS_GABRIEL_FACT_1', 'Gabriel regards maps as promises about where knowledge will be available later.'),
('TXT_KEY_CIVILOPEDIA_LEADERS_GABRIEL_FACT_2', 'The Colony''s decisions emerge from many local observations rather than a single chain of command.'),

('TXT_KEY_IMPROVEMENT_GABRIEL_COLONY_NODE', 'Colony Node'),
('TXT_KEY_IMPROVEMENT_GABRIEL_COLONY_NODE_HELP', '+1 [ICON_RESEARCH] Science and +1 [ICON_PRODUCTION] Production. Reveals adjacent tiles. Gabriel''s military units on or adjacent to an active Node gain +3% Combat Strength, +5% attacking strength, and +3 healing. An active Node adjacent to a Colony city grants it +1% Science and +1% Defensive Strength; a Colony Nexus adds +1 Science per adjacent Node. Pillaged Nodes provide none of these network effects.'),
('TXT_KEY_IMPROVEMENT_GABRIEL_COLONY_NODE_PEDIA', 'A Colony Node is an established formicarium, observation post, supply chamber, and information relay. Every Colony city prepares one independently over a game-speed-scaled interval. A ready Node may be placed within three tiles of its city on owned or neutral land, but never in another civilization''s territory. The Node influences its own tile and the six adjacent tiles. Multiple Nodes do not multiply unit bonuses. A Node must be active and unpillaged; if foreign culture permanently claims its plot, the infrastructure is dismantled.[NEWLINE][NEWLINE]Strategy: place some Nodes adjacent to cities for Science and defense, and others along chokepoints for vision, healing, and prepared firing positions. The strongest network is not the densest possible cluster, but one whose coverage supports where your army will actually fight.'),

('TXT_KEY_UNIT_GABRIEL_SWARM_HOST', 'Swarm Host'),
('TXT_KEY_UNIT_GABRIEL_SWARM_HOST_HELP', 'Unique Colony ranged unit replacing the Composite Bowman. Has exactly 1 less Ranged Combat Strength than the active Community Patch unit it replaces. Damaging an enemy military unit applies one stack of Infestation: -5% Combat Strength for 2 turns, up to 3 stacks; further hits refresh the duration. Gains +8% Combat Strength inside an active Colony Node network.'),
('TXT_KEY_UNIT_GABRIEL_SWARM_HOST_STRATEGY', 'Use Swarm Hosts from prepared firing positions. Focus several attacks on the most dangerous enemy to reach -15% Combat Strength, then let front-line units finish the engagement. Their lower base Ranged Strength and dependence on Node coverage make them poor rush units far from home. Protect them, rotate damaged units through Node healing positions, and refresh Infestation before it expires.'),
('TXT_KEY_UNIT_GABRIEL_SWARM_HOST_PEDIA', 'Swarm Hosts carry sealed formicaria and specialized colonies selected for disruption rather than direct killing power. Clouds of workers enter gaps in armor, spoil supplies, disturb formations, and force an opponent to fight while attending to a thousand small failures.[NEWLINE][NEWLINE]Gameplay: the Swarm Host retains the movement, range, cost, prerequisites, AI role, upgrade path, and combat class of the active Community Patch Composite Bowman, but has one less Ranged Combat Strength. Any successful hit on a military unit adds or refreshes Infestation. Its Swarm Reinforcement bonus functions only within active Colony Node influence.'),

('TXT_KEY_BUILDING_GABRIEL_COLONY_NEXUS', 'Colony Nexus'),
('TXT_KEY_BUILDING_GABRIEL_COLONY_NEXUS_HELP', 'Unique University replacement. Retains all effects of the active Community Patch University, adds +1 Great Scientist Point, and provides +1 [ICON_RESEARCH] Science for every active Colony Node adjacent to this city. Military units within those connected Nodes detect submarines.'),
('TXT_KEY_BUILDING_GABRIEL_COLONY_NEXUS_STRATEGY', 'The Colony Nexus is strongest in a mature city ringed by Nodes, but remains a complete University even without them. Build it in every serious research city. Its detection network is local: only active Nodes adjacent to a Nexus city enable detection, so a pillaged link can open a surveillance gap.'),
('TXT_KEY_BUILDING_GABRIEL_COLONY_NEXUS_PEDIA', 'The Colony Nexus joins human scholarship to the distributed observation of nearby formicaria. It inherits every ordinary effect of the current Community Patch University, including later balance changes, and adds one flat Great Scientist Point per turn.[NEWLINE][NEWLINE]For each active, unpillaged Colony Node directly adjacent to its city, the Nexus supplies one additional Science. Those same connected Nodes form a detection network. Colony military units standing within their influence gain the ability to detect submarines. A Node adjacent to two Nexus cities may support both.'),

('TXT_KEY_PROMOTION_GABRIEL_COLONY_NETWORK', 'Inside the Colony Network'),
('TXT_KEY_PROMOTION_GABRIEL_COLONY_NETWORK_HELP', '+3% Combat Strength, +5% attacking strength, and +3 HP whenever this unit normally heals. Does not stack from overlapping Nodes.'),
('TXT_KEY_PROMOTION_GABRIEL_SWARM_REINFORCEMENT', 'Swarm Reinforcement'),
('TXT_KEY_PROMOTION_GABRIEL_SWARM_REINFORCEMENT_HELP', '+8% Combat Strength while within active Colony Node influence.'),
('TXT_KEY_PROMOTION_GABRIEL_INFESTATION_SOURCE', 'Infestation'),
('TXT_KEY_PROMOTION_GABRIEL_INFESTATION_SOURCE_HELP', 'Damaging an enemy military unit applies -5% Combat Strength for 2 turns, stacking up to -15%. Additional hits refresh the duration.'),
('TXT_KEY_PROMOTION_GABRIEL_INFESTATION_1', 'Infestation I'),
('TXT_KEY_PROMOTION_GABRIEL_INFESTATION_1_HELP', '-5% Combat Strength. Lasts 2 turns; further Swarm Host hits add a stack and refresh duration.'),
('TXT_KEY_PROMOTION_GABRIEL_INFESTATION_2', 'Infestation II'),
('TXT_KEY_PROMOTION_GABRIEL_INFESTATION_2_HELP', '-10% Combat Strength. Lasts 2 turns; further Swarm Host hits add a stack and refresh duration.'),
('TXT_KEY_PROMOTION_GABRIEL_INFESTATION_3', 'Infestation III'),
('TXT_KEY_PROMOTION_GABRIEL_INFESTATION_3_HELP', '-15% Combat Strength. Lasts 2 turns; further Swarm Host hits refresh duration.'),
('TXT_KEY_PROMOTION_GABRIEL_NEXUS_DETECTION', 'Nexus Detection Network'),
('TXT_KEY_PROMOTION_GABRIEL_NEXUS_DETECTION_HELP', 'Detects submarines while this unit occupies an active Colony Node network connected to a city with a Colony Nexus.'),
('TXT_KEY_BUILDING_GABRIEL_NETWORK_DUMMY', 'Colony Network (Internal)'),

('TXT_KEY_GABRIEL_NODE_READY_TITLE', 'Colony Node Ready — {1_CityName}'),
('TXT_KEY_GABRIEL_NODE_READY_BODY', '{1_CityName} has completed a Colony Node. Choose an eligible plot within three tiles. Its generation timer is paused until the Node is placed.'),
('TXT_KEY_GABRIEL_NODE_NO_PLOTS', 'No legal Colony Node plots are currently available near {1_CityName}.'),
('TXT_KEY_GABRIEL_NODE_PANEL_TITLE', 'Colony Node Ready'),
('TXT_KEY_GABRIEL_NODE_PANEL_INSTRUCTIONS', 'Choose a highlighted plot within three tiles of {1_CityName}. Owned and neutral land are valid; foreign territory, cities, water, mountains, natural wonders, resources, and valuable improvements are not.'),
('TXT_KEY_GABRIEL_NODE_PREVIOUS', 'Previous'),
('TXT_KEY_GABRIEL_NODE_NEXT', 'Next'),
('TXT_KEY_GABRIEL_NODE_PLACE', 'Establish Node'),
('TXT_KEY_GABRIEL_NODE_LATER', 'Later'),
('TXT_KEY_GABRIEL_NODE_PLACED', 'Colony Node established near {1_CityName}.'),
('TXT_KEY_GABRIEL_NODE_INVALID', 'That plot is no longer eligible. Choose another location.'),
('TXT_KEY_GABRIEL_NODE_UNOWNED', 'Unowned'),
('TXT_KEY_GABRIEL_NODE_OWNED', 'Your Territory'),
('TXT_KEY_GABRIEL_NETWORK_PANEL_TITLE', 'Colony Network'),
('TXT_KEY_GABRIEL_NETWORK_PANEL_SUBTITLE', 'Preparation turns territory into knowledge, vision, and strength.'),
('TXT_KEY_GABRIEL_NETWORK_ACTIVE_NODES', 'Active Nodes'),
('TXT_KEY_GABRIEL_NETWORK_READY_CITIES', 'Ready Cities'),
('TXT_KEY_GABRIEL_NETWORK_COVERED_UNITS', 'Covered Forces'),
('TXT_KEY_GABRIEL_NETWORK_SELECT_CITY', 'Inspect Colony City'),
('TXT_KEY_GABRIEL_NETWORK_PREPARATION', 'Node Preparation'),
('TXT_KEY_GABRIEL_NETWORK_CONNECTIONS', 'Local Connections'),
('TXT_KEY_GABRIEL_NETWORK_EFFECTS', 'Network Effects'),
('TXT_KEY_GABRIEL_NETWORK_REFRESH', 'Refresh'),
('TXT_KEY_GABRIEL_NETWORK_CLOSE', 'Close'),
('TXT_KEY_GABRIEL_NETWORK_VIEW_CITY', 'View City'),
('TXT_KEY_GABRIEL_NETWORK_PLACE_READY', 'Place Ready Node'),

('TXT_KEY_CITY_GABRIEL_PRIME_CHAMBER', 'Prime Chamber'),
('TXT_KEY_CITY_GABRIEL_FORMICARIUM', 'Formicarium'),
('TXT_KEY_CITY_GABRIEL_AMBER_VAULT', 'Amber Vault'),
('TXT_KEY_CITY_GABRIEL_SIX_PATHS', 'Six Paths'),
('TXT_KEY_CITY_GABRIEL_QUIET_REACH', 'Quiet Reach'),
('TXT_KEY_CITY_GABRIEL_DEEP_NURSERY', 'Deep Nursery'),
('TXT_KEY_CITY_GABRIEL_WATCHER_HILL', 'Watcher Hill'),
('TXT_KEY_CITY_GABRIEL_LONG_TRAIL', 'Long Trail'),
('TXT_KEY_CITY_GABRIEL_PATIENT_GATE', 'Patient Gate'),
('TXT_KEY_CITY_GABRIEL_SHARED_PURPOSE', 'Shared Purpose'),
('TXT_KEY_CITY_GABRIEL_ROOT_COUNCIL', 'Root Council'),
('TXT_KEY_CITY_GABRIEL_LANTERN_NEST', 'Lantern Nest'),
('TXT_KEY_SPY_GABRIEL_SCOUT_ONE', 'Myrmex'),
('TXT_KEY_SPY_GABRIEL_SCOUT_TWO', 'Tessera'),
('TXT_KEY_SPY_GABRIEL_SCOUT_THREE', 'Antenna'),
('TXT_KEY_SPY_GABRIEL_SCOUT_FOUR', 'Mandible'),

('TXT_KEY_LEADER_GABRIEL_FIRSTGREETING_1', 'We are many, though you see only one voice. I am Gabriel. If your purpose permits patience, our paths may strengthen one another.'),
('TXT_KEY_LEADER_GABRIEL_GREETING_FRIENDLY_1', 'Your signal is welcome. What shall our colonies prepare together?'),
('TXT_KEY_LEADER_GABRIEL_GREETING_NEUTRAL_1', 'You have my attention. State what you need, and what you are prepared to offer.'),
('TXT_KEY_LEADER_GABRIEL_GREETING_HOSTILE_1', 'Noise is not strength. Continue, if you wish us to measure yours.'),
('TXT_KEY_LEADER_GABRIEL_DECLAREWAR_1', 'Every trail has been marked, every chamber supplied. This outcome was prepared before you noticed it.'),
('TXT_KEY_LEADER_GABRIEL_ATTACKED_1', 'You gamble against ground you have not studied. The Colony does not.'),
('TXT_KEY_LEADER_GABRIEL_LOSEWAR_1', 'You have found the weak chamber. Enough loss; let us repair what remains.'),
('TXT_KEY_LEADER_GABRIEL_WINWAR_1', 'The field now says what I expected it to say. Accept peace, and we need not prove it again.'),
('TXT_KEY_LEADER_GABRIEL_DEFEATED_1', 'A colony may be scattered without being erased. Remember that when the quiet places begin to move.'),

('TXT_KEY_CIV5_GABRIEL_TITLE', 'The Colony'),
('TXT_KEY_CIV5_GABRIEL_HEADING_1', 'Many Minds, One Purpose'),
('TXT_KEY_CIV5_GABRIEL_TEXT_1', 'The Colony is a distributed civilization organized around observation, preparation, and shared purpose. Its roads resemble trails, its universities are living information nexuses, and its border works descend into chambered formicaria beneath the soil. Gabriel does not command isolated subjects; he interprets thousands of signals and arranges the conditions in which every part can act.'),
('TXT_KEY_CIV5_GABRIEL_HEADING_2', 'Colony Network'),
('TXT_KEY_CIV5_GABRIEL_TEXT_2', 'Every city prepares Colony Nodes over time. Active Nodes provide Science, Production, adjacent vision, healing, and combat strength. Nodes beside cities also improve Science and defensive strength. The benefit to units does not stack, so careful coverage matters more than piling every Node into one place.'),
('TXT_KEY_CIV5_GABRIEL_HEADING_3', 'Colony Nexus'),
('TXT_KEY_CIV5_GABRIEL_TEXT_3', 'The Colony Nexus replaces the University and retains its normal Community Patch effects. It adds a Great Scientist Point and gains additional Science from every active adjacent Node. Connected Nodes also let nearby military units detect submarines.'),
('TXT_KEY_CIV5_GABRIEL_HEADING_4', 'Swarm Hosts and Infestation'),
('TXT_KEY_CIV5_GABRIEL_TEXT_4', 'Swarm Hosts replace Composite Bowmen. Their direct ranged strength is slightly lower, but successful attacks apply Infestation for two turns. Repeated hits deepen the penalty to a maximum of -15% Combat Strength, allowing the Colony to dismantle dangerous formations methodically.'),
('TXT_KEY_CIV5_GABRIEL_HEADING_5', 'Strategy'),
('TXT_KEY_CIV5_GABRIEL_TEXT_5', 'Prepare chokepoints before war, keep critical Nodes repaired, and build Colony Nexuses in cities with strong local connections. Science is the natural victory route. Diplomacy benefits from the same resilient research base, while Domination works best as a measured counteroffensive from prepared territory.'),
('TXT_KEY_CIV5_GABRIEL_FACTOID_HEADING', 'Preparation'),
('TXT_KEY_CIV5_GABRIEL_FACTOID_TEXT', 'The Colony treats information as infrastructure. Its Nodes are observation posts, supply chambers, healing positions, and scientific relays at once.'),
('TXT_KEY_CIV5_GABRIEL_STRATEGY_HEADING', 'Colony Network'),
('TXT_KEY_CIV5_GABRIEL_STRATEGY_TEXT', 'Gabriel excels at Science and prepared defense. Rush him before Nodes mature, pillage established networks, attack from multiple directions, or force his army to fight far from home.'),
('TXT_KEY_CIV5_GABRIEL_VICTORY_HEADING', 'Victory Guidance'),
('TXT_KEY_CIV5_GABRIEL_VICTORY_TEXT', 'Science: Excellent. Diplomacy: Strong. Domination: Viable through counterattack. Culture: Viable but receives no direct specialization.');
